version: "3.5"
services:
  beacon-chain:
    image: "beacon-chain.prysm-ropsten.dnp.dappnode.eth:1.0.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.3
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "19514:19514/tcp"
      - "18514:18514/udp"
    restart: unless-stopped
    environment:
      HTTP_WEB3PROVIDER: "http://ropsten-geth.dappnode:8551"
      TTD_OVERRIDE: 50000000000000000
      CORSDOMAIN: "http://prysm-ropsten.dappnode"
      WEB3_BACKUP: ""
      P2P_TCP_PORT: 19514
      P2P_UDP_PORT: 18514
      EXTRA_OPTS: ""
volumes:
  beacon-chain-data: {}
